#pragma  once
#include "queue.cpp"
#include "stack.cpp"
#include "list.cpp"
#include "btree.cpp"
#include "bstree.cpp"
#include "bbtree.cpp"
#include "heap.cpp"
#include "normal.cpp"
#include "normal2.h"
#include "iterator.cpp"
#include <algorithm>
#include <math.h>